export const GET_CAMPAIGN_WITH_USER  = 'GET_CAMPAIGN_WITH_USER'
export const SEARCH_CAMPAIGN_BY_NAME = 'SEARCH_CAMPAIGN_BY_NAME'
export const SEARCH_CAMPAIGN_BY_DATE = 'SEARCH_CAMPAIGN_BY_DATE' 
export const DISPLAY_LOADER  = 'DISPLAY_LOADER'