export const GET_CAMPAIGN  = 'GET_CAMPAIGN'
export const SEARCH_CAMPAIGN_BY_NAME = 'SEARCH_CAMPAIGN_BY_NAME'
export const SEARCH_CAMPAIGN_BY_DATE = 'SEARCH_CAMPAIGN_BY_DATE' 
export const DISPLAY_LOADER  = 'DISPLAY_LOADER'